package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class ChickenCureTaskDO implements Serializable {
    /**
     *
     * 
     * chicken_cure_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * 小鸡编号
     * chicken_cure_task.chicken_num
     *
     * @mbg.generated
     */
    private String chickenNum;

    /**
     *
     * 用户编号
     * chicken_cure_task.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 任务类型：1-邀请好友|2-有效消费|3-帮助好友喂食和打扫|4-鸡蛋兑换
     * chicken_cure_task.task_type
     *
     * @mbg.generated
     */
    private Byte taskType;

    /**
     *
     * 进度
     * chicken_cure_task.progress
     *
     * @mbg.generated
     */
    private Integer progress;

    /**
     *
     * 是否
     * chicken_cure_task.is_finished
     *
     * @mbg.generated
     */
    private Boolean isFinished;

    /**
     *
     * 关联用户ID，多个时逗号隔开
     * chicken_cure_task.relate_member_ids
     *
     * @mbg.generated
     */
    private String relateMemberIds;

    /**
     *
     * 修改时间
     * chicken_cure_task.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * 创建时间
     * chicken_cure_task.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.id
     *
     * @return the value of chicken_cure_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.id
     *
     * @param id the value for chicken_cure_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.chicken_num
     *
     * @return the value of chicken_cure_task.chicken_num
     *
     * @mbg.generated
     */
    public String getChickenNum() {
        return chickenNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.chicken_num
     *
     * @param chickenNum the value for chicken_cure_task.chicken_num
     *
     * @mbg.generated
     */
    public void setChickenNum(String chickenNum) {
        this.chickenNum = chickenNum == null ? null : chickenNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.member_num
     *
     * @return the value of chicken_cure_task.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.member_num
     *
     * @param memberNum the value for chicken_cure_task.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.task_type
     *
     * @return the value of chicken_cure_task.task_type
     *
     * @mbg.generated
     */
    public Byte getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.task_type
     *
     * @param taskType the value for chicken_cure_task.task_type
     *
     * @mbg.generated
     */
    public void setTaskType(Byte taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.progress
     *
     * @return the value of chicken_cure_task.progress
     *
     * @mbg.generated
     */
    public Integer getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.progress
     *
     * @param progress the value for chicken_cure_task.progress
     *
     * @mbg.generated
     */
    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.is_finished
     *
     * @return the value of chicken_cure_task.is_finished
     *
     * @mbg.generated
     */
    public Boolean getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.is_finished
     *
     * @param isFinished the value for chicken_cure_task.is_finished
     *
     * @mbg.generated
     */
    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.relate_member_ids
     *
     * @return the value of chicken_cure_task.relate_member_ids
     *
     * @mbg.generated
     */
    public String getRelateMemberIds() {
        return relateMemberIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.relate_member_ids
     *
     * @param relateMemberIds the value for chicken_cure_task.relate_member_ids
     *
     * @mbg.generated
     */
    public void setRelateMemberIds(String relateMemberIds) {
        this.relateMemberIds = relateMemberIds == null ? null : relateMemberIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.gmt_modify
     *
     * @return the value of chicken_cure_task.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.gmt_modify
     *
     * @param gmtModify the value for chicken_cure_task.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken_cure_task.gmt_create
     *
     * @return the value of chicken_cure_task.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken_cure_task.gmt_create
     *
     * @param gmtCreate the value for chicken_cure_task.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}