package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ChickenDO implements Serializable {
    /**
     *
     * 主键
     * chicken.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 小鸡编号
     * chicken.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * 所属用户编号
     * chicken.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 名称
     * chicken.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 所处时期，0成长期，1半成熟期，2成熟期，3生病，4治疗中，5死亡
     * chicken.period
     *
     * @mbg.generated
     */
    private Byte period;

    /**
     *
     * 状态，0活动，1睡眠，2饥饿，3饿晕
     * chicken.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 是否放养，0否，1是
     * chicken.is_outside
     *
     * @mbg.generated
     */
    private Boolean isOutside;

    /**
     *
     * 是否进入产房，0否，1是
     * chicken.is_pregnant
     *
     * @mbg.generated
     */
    private Boolean isPregnant;

    /**
     *
     * 愉悦值
     * chicken.joyful_val
     *
     * @mbg.generated
     */
    private Integer joyfulVal;

    /**
     *
     * 饱腹值
     * chicken.full_val
     *
     * @mbg.generated
     */
    private Integer fullVal;

    /**
     *
     * 成长值
     * chicken.growth_val
     *
     * @mbg.generated
     */
    private Integer growthVal;

    /**
     *
     * 清洁度
     * chicken.cleanness_val
     *
     * @mbg.generated
     */
    private Integer cleannessVal;

    /**
     *
     * 愉悦值快照
     * chicken.joyful_val_snapshoot
     *
     * @mbg.generated
     */
    private Integer joyfulValSnapshoot;

    /**
     *
     * 鸡舍清洁度-愉悦值更新时间
     * chicken.joyful_house_clean_time
     *
     * @mbg.generated
     */
    private Date joyfulHouseCleanTime;

    /**
     *
     * 处于牧场-愉悦值更新时间
     * chicken.joyful_rangeland_site_time
     *
     * @mbg.generated
     */
    private Date joyfulRangelandSiteTime;

    /**
     *
     * 牧场清洁度-愉悦值更新时间
     * chicken.joyful_rangeland_clean_time
     *
     * @mbg.generated
     */
    private Date joyfulRangelandCleanTime;

    /**
     *
     * 饱腹值-周期更新时间
     * chicken.full_period_time
     *
     * @mbg.generated
     */
    private Date fullPeriodTime;

    /**
     *
     * 最新分配产蛋数
     * chicken.lay_eggs
     *
     * @mbg.generated
     */
    private BigDecimal layEggs;

    /**
     *
     * 蛋窝鸡蛋数量
     * chicken.house_eggs
     *
     * @mbg.generated
     */
    private BigDecimal houseEggs;

    /**
     *
     * 真实操作的鸡蛋数量
     * chicken.real_opt_eggs
     *
     * @mbg.generated
     */
    private BigDecimal realOptEggs;

    /**
     *
     * 生命周期计时起点
     * chicken.life_start_time
     *
     * @mbg.generated
     */
    private Date lifeStartTime;

    /**
     *
     * 小鸡处于鸡窝计时开始时间
     * chicken.inhouse_time
     *
     * @mbg.generated
     */
    private Date inhouseTime;

    /**
     *
     * 小鸡在鸡窝总时长，单位分钟
     * chicken.inhouse_duration
     *
     * @mbg.generated
     */
    private Integer inhouseDuration;

    /**
     *
     * 上次清洁度打扫时间
     * chicken.house_clean_time
     *
     * @mbg.generated
     */
    private Date houseCleanTime;

    /**
     *
     * 未打扫总时长，单位分钟
     * chicken.house_unclean_duration
     *
     * @mbg.generated
     */
    private Integer houseUncleanDuration;

    /**
     *
     * 清洁度过期时间
     * chicken.cleanness_invalid_time
     *
     * @mbg.generated
     */
    private Date cleannessInvalidTime;

    /**
     *
     * 更新时间
     * chicken.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * chicken.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chicken
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.id
     *
     * @return the value of chicken.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.id
     *
     * @param id the value for chicken.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.num
     *
     * @return the value of chicken.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.num
     *
     * @param num the value for chicken.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.member_num
     *
     * @return the value of chicken.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.member_num
     *
     * @param memberNum the value for chicken.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.name
     *
     * @return the value of chicken.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.name
     *
     * @param name the value for chicken.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.period
     *
     * @return the value of chicken.period
     *
     * @mbg.generated
     */
    public Byte getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.period
     *
     * @param period the value for chicken.period
     *
     * @mbg.generated
     */
    public void setPeriod(Byte period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.status
     *
     * @return the value of chicken.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.status
     *
     * @param status the value for chicken.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.is_outside
     *
     * @return the value of chicken.is_outside
     *
     * @mbg.generated
     */
    public Boolean getIsOutside() {
        return isOutside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.is_outside
     *
     * @param isOutside the value for chicken.is_outside
     *
     * @mbg.generated
     */
    public void setIsOutside(Boolean isOutside) {
        this.isOutside = isOutside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.is_pregnant
     *
     * @return the value of chicken.is_pregnant
     *
     * @mbg.generated
     */
    public Boolean getIsPregnant() {
        return isPregnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.is_pregnant
     *
     * @param isPregnant the value for chicken.is_pregnant
     *
     * @mbg.generated
     */
    public void setIsPregnant(Boolean isPregnant) {
        this.isPregnant = isPregnant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.joyful_val
     *
     * @return the value of chicken.joyful_val
     *
     * @mbg.generated
     */
    public Integer getJoyfulVal() {
        return joyfulVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.joyful_val
     *
     * @param joyfulVal the value for chicken.joyful_val
     *
     * @mbg.generated
     */
    public void setJoyfulVal(Integer joyfulVal) {
        this.joyfulVal = joyfulVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.full_val
     *
     * @return the value of chicken.full_val
     *
     * @mbg.generated
     */
    public Integer getFullVal() {
        return fullVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.full_val
     *
     * @param fullVal the value for chicken.full_val
     *
     * @mbg.generated
     */
    public void setFullVal(Integer fullVal) {
        this.fullVal = fullVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.growth_val
     *
     * @return the value of chicken.growth_val
     *
     * @mbg.generated
     */
    public Integer getGrowthVal() {
        return growthVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.growth_val
     *
     * @param growthVal the value for chicken.growth_val
     *
     * @mbg.generated
     */
    public void setGrowthVal(Integer growthVal) {
        this.growthVal = growthVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.cleanness_val
     *
     * @return the value of chicken.cleanness_val
     *
     * @mbg.generated
     */
    public Integer getCleannessVal() {
        return cleannessVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.cleanness_val
     *
     * @param cleannessVal the value for chicken.cleanness_val
     *
     * @mbg.generated
     */
    public void setCleannessVal(Integer cleannessVal) {
        this.cleannessVal = cleannessVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.joyful_val_snapshoot
     *
     * @return the value of chicken.joyful_val_snapshoot
     *
     * @mbg.generated
     */
    public Integer getJoyfulValSnapshoot() {
        return joyfulValSnapshoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.joyful_val_snapshoot
     *
     * @param joyfulValSnapshoot the value for chicken.joyful_val_snapshoot
     *
     * @mbg.generated
     */
    public void setJoyfulValSnapshoot(Integer joyfulValSnapshoot) {
        this.joyfulValSnapshoot = joyfulValSnapshoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.joyful_house_clean_time
     *
     * @return the value of chicken.joyful_house_clean_time
     *
     * @mbg.generated
     */
    public Date getJoyfulHouseCleanTime() {
        return joyfulHouseCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.joyful_house_clean_time
     *
     * @param joyfulHouseCleanTime the value for chicken.joyful_house_clean_time
     *
     * @mbg.generated
     */
    public void setJoyfulHouseCleanTime(Date joyfulHouseCleanTime) {
        this.joyfulHouseCleanTime = joyfulHouseCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.joyful_rangeland_site_time
     *
     * @return the value of chicken.joyful_rangeland_site_time
     *
     * @mbg.generated
     */
    public Date getJoyfulRangelandSiteTime() {
        return joyfulRangelandSiteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.joyful_rangeland_site_time
     *
     * @param joyfulRangelandSiteTime the value for chicken.joyful_rangeland_site_time
     *
     * @mbg.generated
     */
    public void setJoyfulRangelandSiteTime(Date joyfulRangelandSiteTime) {
        this.joyfulRangelandSiteTime = joyfulRangelandSiteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.joyful_rangeland_clean_time
     *
     * @return the value of chicken.joyful_rangeland_clean_time
     *
     * @mbg.generated
     */
    public Date getJoyfulRangelandCleanTime() {
        return joyfulRangelandCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.joyful_rangeland_clean_time
     *
     * @param joyfulRangelandCleanTime the value for chicken.joyful_rangeland_clean_time
     *
     * @mbg.generated
     */
    public void setJoyfulRangelandCleanTime(Date joyfulRangelandCleanTime) {
        this.joyfulRangelandCleanTime = joyfulRangelandCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.full_period_time
     *
     * @return the value of chicken.full_period_time
     *
     * @mbg.generated
     */
    public Date getFullPeriodTime() {
        return fullPeriodTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.full_period_time
     *
     * @param fullPeriodTime the value for chicken.full_period_time
     *
     * @mbg.generated
     */
    public void setFullPeriodTime(Date fullPeriodTime) {
        this.fullPeriodTime = fullPeriodTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.lay_eggs
     *
     * @return the value of chicken.lay_eggs
     *
     * @mbg.generated
     */
    public BigDecimal getLayEggs() {
        return layEggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.lay_eggs
     *
     * @param layEggs the value for chicken.lay_eggs
     *
     * @mbg.generated
     */
    public void setLayEggs(BigDecimal layEggs) {
        this.layEggs = layEggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.house_eggs
     *
     * @return the value of chicken.house_eggs
     *
     * @mbg.generated
     */
    public BigDecimal getHouseEggs() {
        return houseEggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.house_eggs
     *
     * @param houseEggs the value for chicken.house_eggs
     *
     * @mbg.generated
     */
    public void setHouseEggs(BigDecimal houseEggs) {
        this.houseEggs = houseEggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.real_opt_eggs
     *
     * @return the value of chicken.real_opt_eggs
     *
     * @mbg.generated
     */
    public BigDecimal getRealOptEggs() {
        return realOptEggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.real_opt_eggs
     *
     * @param realOptEggs the value for chicken.real_opt_eggs
     *
     * @mbg.generated
     */
    public void setRealOptEggs(BigDecimal realOptEggs) {
        this.realOptEggs = realOptEggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.life_start_time
     *
     * @return the value of chicken.life_start_time
     *
     * @mbg.generated
     */
    public Date getLifeStartTime() {
        return lifeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.life_start_time
     *
     * @param lifeStartTime the value for chicken.life_start_time
     *
     * @mbg.generated
     */
    public void setLifeStartTime(Date lifeStartTime) {
        this.lifeStartTime = lifeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.inhouse_time
     *
     * @return the value of chicken.inhouse_time
     *
     * @mbg.generated
     */
    public Date getInhouseTime() {
        return inhouseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.inhouse_time
     *
     * @param inhouseTime the value for chicken.inhouse_time
     *
     * @mbg.generated
     */
    public void setInhouseTime(Date inhouseTime) {
        this.inhouseTime = inhouseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.inhouse_duration
     *
     * @return the value of chicken.inhouse_duration
     *
     * @mbg.generated
     */
    public Integer getInhouseDuration() {
        return inhouseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.inhouse_duration
     *
     * @param inhouseDuration the value for chicken.inhouse_duration
     *
     * @mbg.generated
     */
    public void setInhouseDuration(Integer inhouseDuration) {
        this.inhouseDuration = inhouseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.house_clean_time
     *
     * @return the value of chicken.house_clean_time
     *
     * @mbg.generated
     */
    public Date getHouseCleanTime() {
        return houseCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.house_clean_time
     *
     * @param houseCleanTime the value for chicken.house_clean_time
     *
     * @mbg.generated
     */
    public void setHouseCleanTime(Date houseCleanTime) {
        this.houseCleanTime = houseCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.house_unclean_duration
     *
     * @return the value of chicken.house_unclean_duration
     *
     * @mbg.generated
     */
    public Integer getHouseUncleanDuration() {
        return houseUncleanDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.house_unclean_duration
     *
     * @param houseUncleanDuration the value for chicken.house_unclean_duration
     *
     * @mbg.generated
     */
    public void setHouseUncleanDuration(Integer houseUncleanDuration) {
        this.houseUncleanDuration = houseUncleanDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.cleanness_invalid_time
     *
     * @return the value of chicken.cleanness_invalid_time
     *
     * @mbg.generated
     */
    public Date getCleannessInvalidTime() {
        return cleannessInvalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.cleanness_invalid_time
     *
     * @param cleannessInvalidTime the value for chicken.cleanness_invalid_time
     *
     * @mbg.generated
     */
    public void setCleannessInvalidTime(Date cleannessInvalidTime) {
        this.cleannessInvalidTime = cleannessInvalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.gmt_modified
     *
     * @return the value of chicken.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.gmt_modified
     *
     * @param gmtModified the value for chicken.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chicken.gmt_create
     *
     * @return the value of chicken.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chicken.gmt_create
     *
     * @param gmtCreate the value for chicken.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}