package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EggExchangeRecordDO implements Serializable {
    /**
     *
     * 主键
     * egg_exchange_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 兑换编号
     * egg_exchange_record.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * 用户编号
     * egg_exchange_record.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 类型，0红包，1礼品
     * egg_exchange_record.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 兑换鸡蛋数量
     * egg_exchange_record.egg_quantity
     *
     * @mbg.generated
     */
    private BigDecimal eggQuantity;

    /**
     *
     * 兑换金额
     * egg_exchange_record.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * 礼品id
     * egg_exchange_record.gift_id
     *
     * @mbg.generated
     */
    private Long giftId;

    /**
     *
     * 礼品名称
     * egg_exchange_record.gift_name
     *
     * @mbg.generated
     */
    private String giftName;

    /**
     *
     * 礼品图片
     * egg_exchange_record.gift_img_path
     *
     * @mbg.generated
     */
    private String giftImgPath;

    /**
     *
     * 类型，0待处理，1发放失败，2已发放，3已到账，4已退款
     * egg_exchange_record.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 姓名
     * egg_exchange_record.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 手机号码
     * egg_exchange_record.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * 收货地址
     * egg_exchange_record.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * 物流单号
     * egg_exchange_record.express_num
     *
     * @mbg.generated
     */
    private String expressNum;

    /**
     *
     * 备注
     * egg_exchange_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * 发放时间
     * egg_exchange_record.gmt_send
     *
     * @mbg.generated
     */
    private Date gmtSend;

    /**
     *
     * 更新时间
     * egg_exchange_record.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * egg_exchange_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.id
     *
     * @return the value of egg_exchange_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.id
     *
     * @param id the value for egg_exchange_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.num
     *
     * @return the value of egg_exchange_record.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.num
     *
     * @param num the value for egg_exchange_record.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.member_num
     *
     * @return the value of egg_exchange_record.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.member_num
     *
     * @param memberNum the value for egg_exchange_record.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.type
     *
     * @return the value of egg_exchange_record.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.type
     *
     * @param type the value for egg_exchange_record.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.egg_quantity
     *
     * @return the value of egg_exchange_record.egg_quantity
     *
     * @mbg.generated
     */
    public BigDecimal getEggQuantity() {
        return eggQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.egg_quantity
     *
     * @param eggQuantity the value for egg_exchange_record.egg_quantity
     *
     * @mbg.generated
     */
    public void setEggQuantity(BigDecimal eggQuantity) {
        this.eggQuantity = eggQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.amount
     *
     * @return the value of egg_exchange_record.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.amount
     *
     * @param amount the value for egg_exchange_record.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.gift_id
     *
     * @return the value of egg_exchange_record.gift_id
     *
     * @mbg.generated
     */
    public Long getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.gift_id
     *
     * @param giftId the value for egg_exchange_record.gift_id
     *
     * @mbg.generated
     */
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.gift_name
     *
     * @return the value of egg_exchange_record.gift_name
     *
     * @mbg.generated
     */
    public String getGiftName() {
        return giftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.gift_name
     *
     * @param giftName the value for egg_exchange_record.gift_name
     *
     * @mbg.generated
     */
    public void setGiftName(String giftName) {
        this.giftName = giftName == null ? null : giftName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.gift_img_path
     *
     * @return the value of egg_exchange_record.gift_img_path
     *
     * @mbg.generated
     */
    public String getGiftImgPath() {
        return giftImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.gift_img_path
     *
     * @param giftImgPath the value for egg_exchange_record.gift_img_path
     *
     * @mbg.generated
     */
    public void setGiftImgPath(String giftImgPath) {
        this.giftImgPath = giftImgPath == null ? null : giftImgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.status
     *
     * @return the value of egg_exchange_record.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.status
     *
     * @param status the value for egg_exchange_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.name
     *
     * @return the value of egg_exchange_record.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.name
     *
     * @param name the value for egg_exchange_record.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.mobile
     *
     * @return the value of egg_exchange_record.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.mobile
     *
     * @param mobile the value for egg_exchange_record.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.address
     *
     * @return the value of egg_exchange_record.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.address
     *
     * @param address the value for egg_exchange_record.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.express_num
     *
     * @return the value of egg_exchange_record.express_num
     *
     * @mbg.generated
     */
    public String getExpressNum() {
        return expressNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.express_num
     *
     * @param expressNum the value for egg_exchange_record.express_num
     *
     * @mbg.generated
     */
    public void setExpressNum(String expressNum) {
        this.expressNum = expressNum == null ? null : expressNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.remark
     *
     * @return the value of egg_exchange_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.remark
     *
     * @param remark the value for egg_exchange_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.gmt_send
     *
     * @return the value of egg_exchange_record.gmt_send
     *
     * @mbg.generated
     */
    public Date getGmtSend() {
        return gmtSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.gmt_send
     *
     * @param gmtSend the value for egg_exchange_record.gmt_send
     *
     * @mbg.generated
     */
    public void setGmtSend(Date gmtSend) {
        this.gmtSend = gmtSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.gmt_modified
     *
     * @return the value of egg_exchange_record.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.gmt_modified
     *
     * @param gmtModified the value for egg_exchange_record.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column egg_exchange_record.gmt_create
     *
     * @return the value of egg_exchange_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column egg_exchange_record.gmt_create
     *
     * @param gmtCreate the value for egg_exchange_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}