package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class GiftDO implements Serializable {
    /**
     *
     * 主键
     * gift.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 名称
     * gift.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 图片
     * gift.img_path
     *
     * @mbg.generated
     */
    private String imgPath;

    /**
     *
     * 价格
     * gift.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * 库存
     * gift.inventory
     *
     * @mbg.generated
     */
    private Integer inventory;

    /**
     *
     * 1--有效，2--无效
     * gift.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 1--实体，2--虚拟物品
     * gift.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 兑换鸡蛋数量
     * gift.egg_quantity
     *
     * @mbg.generated
     */
    private BigDecimal eggQuantity;

    /**
     *
     * 礼品描述
     * gift.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * 修改时间
     * gift.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * gift.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gift
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.id
     *
     * @return the value of gift.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.id
     *
     * @param id the value for gift.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.name
     *
     * @return the value of gift.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.name
     *
     * @param name the value for gift.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.img_path
     *
     * @return the value of gift.img_path
     *
     * @mbg.generated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.img_path
     *
     * @param imgPath the value for gift.img_path
     *
     * @mbg.generated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.price
     *
     * @return the value of gift.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.price
     *
     * @param price the value for gift.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.inventory
     *
     * @return the value of gift.inventory
     *
     * @mbg.generated
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.inventory
     *
     * @param inventory the value for gift.inventory
     *
     * @mbg.generated
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.status
     *
     * @return the value of gift.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.status
     *
     * @param status the value for gift.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.type
     *
     * @return the value of gift.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.type
     *
     * @param type the value for gift.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.egg_quantity
     *
     * @return the value of gift.egg_quantity
     *
     * @mbg.generated
     */
    public BigDecimal getEggQuantity() {
        return eggQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.egg_quantity
     *
     * @param eggQuantity the value for gift.egg_quantity
     *
     * @mbg.generated
     */
    public void setEggQuantity(BigDecimal eggQuantity) {
        this.eggQuantity = eggQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.description
     *
     * @return the value of gift.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.description
     *
     * @param description the value for gift.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gmt_modified
     *
     * @return the value of gift.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gmt_modified
     *
     * @param gmtModified the value for gift.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift.gmt_create
     *
     * @return the value of gift.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift.gmt_create
     *
     * @param gmtCreate the value for gift.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}