package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class InventoryDO implements Serializable {
    /**
     *
     * 主键
     * inventory.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 商品编号
     * inventory.product_num
     *
     * @mbg.generated
     */
    private String productNum;

    /**
     *
     * 所属用户编号
     * inventory.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 名称
     * inventory.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 数量
     * inventory.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * 类型，0小鸡，1小鸡道具
     * inventory.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 愉悦值
     * inventory.joyful_val
     *
     * @mbg.generated
     */
    private Integer joyfulVal;

    /**
     *
     * 愉悦值是否首次使用生效
     * inventory.is_joyful_first
     *
     * @mbg.generated
     */
    private Boolean isJoyfulFirst;

    /**
     *
     * 愉悦值增加次数上限(0为不限制)
     * inventory.joyful_limit
     *
     * @mbg.generated
     */
    private Integer joyfulLimit;

    /**
     *
     * 成长值
     * inventory.growth_val
     *
     * @mbg.generated
     */
    private Integer growthVal;

    /**
     *
     * 成长值是否首次使用生效
     * inventory.is_growth_first
     *
     * @mbg.generated
     */
    private Boolean isGrowthFirst;

    /**
     *
     * 成长值增加次数上限(0为不限制)
     * inventory.growth_limit
     *
     * @mbg.generated
     */
    private Integer growthLimit;

    /**
     *
     * 饱腹值
     * inventory.full_val
     *
     * @mbg.generated
     */
    private Integer fullVal;

    /**
     *
     * 饱腹值是否首次使用生效
     * inventory.is_full_first
     *
     * @mbg.generated
     */
    private Boolean isFullFirst;

    /**
     *
     * 饱腹值增加次数上限(0为不限制)
     * inventory.full_limit
     *
     * @mbg.generated
     */
    private Integer fullLimit;

    /**
     *
     * 日使用次数限制
     * inventory.day_usage_limit
     *
     * @mbg.generated
     */
    private Integer dayUsageLimit;

    /**
     *
     * 保持清洁度时间（单位：天）
     * inventory.keep_clean_time
     *
     * @mbg.generated
     */
    private Integer keepCleanTime;

    /**
     *
     * 清洁保持时间增加次数上限(0为不限制)
     * inventory.clean_limit
     *
     * @mbg.generated
     */
    private Integer cleanLimit;

    /**
     *
     * 更新时间
     * inventory.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * inventory.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.id
     *
     * @return the value of inventory.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.id
     *
     * @param id the value for inventory.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.product_num
     *
     * @return the value of inventory.product_num
     *
     * @mbg.generated
     */
    public String getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.product_num
     *
     * @param productNum the value for inventory.product_num
     *
     * @mbg.generated
     */
    public void setProductNum(String productNum) {
        this.productNum = productNum == null ? null : productNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.member_num
     *
     * @return the value of inventory.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.member_num
     *
     * @param memberNum the value for inventory.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.name
     *
     * @return the value of inventory.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.name
     *
     * @param name the value for inventory.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.quantity
     *
     * @return the value of inventory.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.quantity
     *
     * @param quantity the value for inventory.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.type
     *
     * @return the value of inventory.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.type
     *
     * @param type the value for inventory.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.joyful_val
     *
     * @return the value of inventory.joyful_val
     *
     * @mbg.generated
     */
    public Integer getJoyfulVal() {
        return joyfulVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.joyful_val
     *
     * @param joyfulVal the value for inventory.joyful_val
     *
     * @mbg.generated
     */
    public void setJoyfulVal(Integer joyfulVal) {
        this.joyfulVal = joyfulVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.is_joyful_first
     *
     * @return the value of inventory.is_joyful_first
     *
     * @mbg.generated
     */
    public Boolean getIsJoyfulFirst() {
        return isJoyfulFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.is_joyful_first
     *
     * @param isJoyfulFirst the value for inventory.is_joyful_first
     *
     * @mbg.generated
     */
    public void setIsJoyfulFirst(Boolean isJoyfulFirst) {
        this.isJoyfulFirst = isJoyfulFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.joyful_limit
     *
     * @return the value of inventory.joyful_limit
     *
     * @mbg.generated
     */
    public Integer getJoyfulLimit() {
        return joyfulLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.joyful_limit
     *
     * @param joyfulLimit the value for inventory.joyful_limit
     *
     * @mbg.generated
     */
    public void setJoyfulLimit(Integer joyfulLimit) {
        this.joyfulLimit = joyfulLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.growth_val
     *
     * @return the value of inventory.growth_val
     *
     * @mbg.generated
     */
    public Integer getGrowthVal() {
        return growthVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.growth_val
     *
     * @param growthVal the value for inventory.growth_val
     *
     * @mbg.generated
     */
    public void setGrowthVal(Integer growthVal) {
        this.growthVal = growthVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.is_growth_first
     *
     * @return the value of inventory.is_growth_first
     *
     * @mbg.generated
     */
    public Boolean getIsGrowthFirst() {
        return isGrowthFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.is_growth_first
     *
     * @param isGrowthFirst the value for inventory.is_growth_first
     *
     * @mbg.generated
     */
    public void setIsGrowthFirst(Boolean isGrowthFirst) {
        this.isGrowthFirst = isGrowthFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.growth_limit
     *
     * @return the value of inventory.growth_limit
     *
     * @mbg.generated
     */
    public Integer getGrowthLimit() {
        return growthLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.growth_limit
     *
     * @param growthLimit the value for inventory.growth_limit
     *
     * @mbg.generated
     */
    public void setGrowthLimit(Integer growthLimit) {
        this.growthLimit = growthLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.full_val
     *
     * @return the value of inventory.full_val
     *
     * @mbg.generated
     */
    public Integer getFullVal() {
        return fullVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.full_val
     *
     * @param fullVal the value for inventory.full_val
     *
     * @mbg.generated
     */
    public void setFullVal(Integer fullVal) {
        this.fullVal = fullVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.is_full_first
     *
     * @return the value of inventory.is_full_first
     *
     * @mbg.generated
     */
    public Boolean getIsFullFirst() {
        return isFullFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.is_full_first
     *
     * @param isFullFirst the value for inventory.is_full_first
     *
     * @mbg.generated
     */
    public void setIsFullFirst(Boolean isFullFirst) {
        this.isFullFirst = isFullFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.full_limit
     *
     * @return the value of inventory.full_limit
     *
     * @mbg.generated
     */
    public Integer getFullLimit() {
        return fullLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.full_limit
     *
     * @param fullLimit the value for inventory.full_limit
     *
     * @mbg.generated
     */
    public void setFullLimit(Integer fullLimit) {
        this.fullLimit = fullLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.day_usage_limit
     *
     * @return the value of inventory.day_usage_limit
     *
     * @mbg.generated
     */
    public Integer getDayUsageLimit() {
        return dayUsageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.day_usage_limit
     *
     * @param dayUsageLimit the value for inventory.day_usage_limit
     *
     * @mbg.generated
     */
    public void setDayUsageLimit(Integer dayUsageLimit) {
        this.dayUsageLimit = dayUsageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.keep_clean_time
     *
     * @return the value of inventory.keep_clean_time
     *
     * @mbg.generated
     */
    public Integer getKeepCleanTime() {
        return keepCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.keep_clean_time
     *
     * @param keepCleanTime the value for inventory.keep_clean_time
     *
     * @mbg.generated
     */
    public void setKeepCleanTime(Integer keepCleanTime) {
        this.keepCleanTime = keepCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.clean_limit
     *
     * @return the value of inventory.clean_limit
     *
     * @mbg.generated
     */
    public Integer getCleanLimit() {
        return cleanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.clean_limit
     *
     * @param cleanLimit the value for inventory.clean_limit
     *
     * @mbg.generated
     */
    public void setCleanLimit(Integer cleanLimit) {
        this.cleanLimit = cleanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.gmt_modified
     *
     * @return the value of inventory.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.gmt_modified
     *
     * @param gmtModified the value for inventory.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.gmt_create
     *
     * @return the value of inventory.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.gmt_create
     *
     * @param gmtCreate the value for inventory.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}