package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MemberDO implements Serializable {
    /**
     *
     * 主键
     * member.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * member.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * 鸡蛋数量
     * member.eggs
     *
     * @mbg.generated
     */
    private BigDecimal eggs;

    /**
     *
     * 更新时间
     * member.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * member.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.num
     *
     * @return the value of member.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.num
     *
     * @param num the value for member.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.eggs
     *
     * @return the value of member.eggs
     *
     * @mbg.generated
     */
    public BigDecimal getEggs() {
        return eggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.eggs
     *
     * @param eggs the value for member.eggs
     *
     * @mbg.generated
     */
    public void setEggs(BigDecimal eggs) {
        this.eggs = eggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_modified
     *
     * @return the value of member.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_modified
     *
     * @param gmtModified the value for member.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gmt_create
     *
     * @return the value of member.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gmt_create
     *
     * @param gmtCreate the value for member.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}