package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class PraySignRewardsDO implements Serializable {
    /**
     *
     * 主键
     * pray_sign_rewards.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 签到记录ID
     * pray_sign_rewards.sign_id
     *
     * @mbg.generated
     */
    private Long signId;

    /**
     *
     * 用户编号
     * pray_sign_rewards.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 是否额外奖励 0否，1是
     * pray_sign_rewards.is_extra
     *
     * @mbg.generated
     */
    private Boolean isExtra;

    /**
     *
     * 商品编号
     * pray_sign_rewards.product_num
     *
     * @mbg.generated
     */
    private String productNum;

    /**
     *
     * 奖励数量
     * pray_sign_rewards.product_count
     *
     * @mbg.generated
     */
    private Integer productCount;

    /**
     *
     * 创建时间
     * pray_sign_rewards.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rewards.id
     *
     * @return the value of pray_sign_rewards.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rewards.id
     *
     * @param id the value for pray_sign_rewards.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rewards.sign_id
     *
     * @return the value of pray_sign_rewards.sign_id
     *
     * @mbg.generated
     */
    public Long getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rewards.sign_id
     *
     * @param signId the value for pray_sign_rewards.sign_id
     *
     * @mbg.generated
     */
    public void setSignId(Long signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rewards.member_num
     *
     * @return the value of pray_sign_rewards.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rewards.member_num
     *
     * @param memberNum the value for pray_sign_rewards.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rewards.is_extra
     *
     * @return the value of pray_sign_rewards.is_extra
     *
     * @mbg.generated
     */
    public Boolean getIsExtra() {
        return isExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rewards.is_extra
     *
     * @param isExtra the value for pray_sign_rewards.is_extra
     *
     * @mbg.generated
     */
    public void setIsExtra(Boolean isExtra) {
        this.isExtra = isExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rewards.product_num
     *
     * @return the value of pray_sign_rewards.product_num
     *
     * @mbg.generated
     */
    public String getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rewards.product_num
     *
     * @param productNum the value for pray_sign_rewards.product_num
     *
     * @mbg.generated
     */
    public void setProductNum(String productNum) {
        this.productNum = productNum == null ? null : productNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rewards.product_count
     *
     * @return the value of pray_sign_rewards.product_count
     *
     * @mbg.generated
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rewards.product_count
     *
     * @param productCount the value for pray_sign_rewards.product_count
     *
     * @mbg.generated
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rewards.gmt_create
     *
     * @return the value of pray_sign_rewards.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rewards.gmt_create
     *
     * @param gmtCreate the value for pray_sign_rewards.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}