package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class PraySignRuleDO implements Serializable {
    /**
     *
     * 主键
     * pray_sign_rule.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 日常获得商品编号
     * pray_sign_rule.product_num
     *
     * @mbg.generated
     */
    private String productNum;

    /**
     *
     * 每日奖励数量
     * pray_sign_rule.product_count
     *
     * @mbg.generated
     */
    private Integer productCount;

    /**
     *
     * 是否根据小鸡数量
     * pray_sign_rule.is_basis_chick
     *
     * @mbg.generated
     */
    private Boolean isBasisChick;

    /**
     *
     * 连续签到天数
     * pray_sign_rule.day
     *
     * @mbg.generated
     */
    private Integer day;

    /**
     *
     * json，额外奖励规则
     * pray_sign_rule.extra
     *
     * @mbg.generated
     */
    private String extra;

    /**
     *
     * 状态，0禁用，1启用
     * pray_sign_rule.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 更新时间
     * pray_sign_rule.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * pray_sign_rule.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.id
     *
     * @return the value of pray_sign_rule.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.id
     *
     * @param id the value for pray_sign_rule.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.product_num
     *
     * @return the value of pray_sign_rule.product_num
     *
     * @mbg.generated
     */
    public String getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.product_num
     *
     * @param productNum the value for pray_sign_rule.product_num
     *
     * @mbg.generated
     */
    public void setProductNum(String productNum) {
        this.productNum = productNum == null ? null : productNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.product_count
     *
     * @return the value of pray_sign_rule.product_count
     *
     * @mbg.generated
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.product_count
     *
     * @param productCount the value for pray_sign_rule.product_count
     *
     * @mbg.generated
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.is_basis_chick
     *
     * @return the value of pray_sign_rule.is_basis_chick
     *
     * @mbg.generated
     */
    public Boolean getIsBasisChick() {
        return isBasisChick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.is_basis_chick
     *
     * @param isBasisChick the value for pray_sign_rule.is_basis_chick
     *
     * @mbg.generated
     */
    public void setIsBasisChick(Boolean isBasisChick) {
        this.isBasisChick = isBasisChick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.day
     *
     * @return the value of pray_sign_rule.day
     *
     * @mbg.generated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.day
     *
     * @param day the value for pray_sign_rule.day
     *
     * @mbg.generated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.extra
     *
     * @return the value of pray_sign_rule.extra
     *
     * @mbg.generated
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.extra
     *
     * @param extra the value for pray_sign_rule.extra
     *
     * @mbg.generated
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.status
     *
     * @return the value of pray_sign_rule.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.status
     *
     * @param status the value for pray_sign_rule.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.gmt_modified
     *
     * @return the value of pray_sign_rule.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.gmt_modified
     *
     * @param gmtModified the value for pray_sign_rule.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pray_sign_rule.gmt_create
     *
     * @return the value of pray_sign_rule.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pray_sign_rule.gmt_create
     *
     * @param gmtCreate the value for pray_sign_rule.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}