package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductDO implements Serializable {
    /**
     *
     * 主键
     * product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 商品编号
     * product.num
     *
     * @mbg.generated
     */
    private String num;

    /**
     *
     * 名称
     * product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * 图片路径
     * product.img_path
     *
     * @mbg.generated
     */
    private String imgPath;

    /**
     *
     * 商品介绍
     * product.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * 原价
     * product.original_price
     *
     * @mbg.generated
     */
    private BigDecimal originalPrice;

    /**
     *
     * 价格
     * product.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * 愉悦值
     * product.joyful_val
     *
     * @mbg.generated
     */
    private Integer joyfulVal;

    /**
     *
     * 愉悦值是否首次使用生效
     * product.is_joyful_first
     *
     * @mbg.generated
     */
    private Boolean isJoyfulFirst;

    /**
     *
     * 愉悦值增加次数上限(0为不限制)
     * product.joyful_limit
     *
     * @mbg.generated
     */
    private Integer joyfulLimit;

    /**
     *
     * 成长值
     * product.growth_val
     *
     * @mbg.generated
     */
    private Integer growthVal;

    /**
     *
     * 成长值是否首次使用生效
     * product.is_growth_first
     *
     * @mbg.generated
     */
    private Boolean isGrowthFirst;

    /**
     *
     * 成长值增加次数上限(0为不限制)
     * product.growth_limit
     *
     * @mbg.generated
     */
    private Integer growthLimit;

    /**
     *
     * 饱腹值
     * product.full_val
     *
     * @mbg.generated
     */
    private Integer fullVal;

    /**
     *
     * 饱腹值是否首次使用生效
     * product.is_full_first
     *
     * @mbg.generated
     */
    private Boolean isFullFirst;

    /**
     *
     * 饱腹值增加次数上限(0为不限制)
     * product.full_limit
     *
     * @mbg.generated
     */
    private Integer fullLimit;

    /**
     *
     * 日使用次数限制
     * product.day_usage_limit
     *
     * @mbg.generated
     */
    private Integer dayUsageLimit;

    /**
     *
     * 保持清洁度时间（单位：天）
     * product.keep_clean_time
     *
     * @mbg.generated
     */
    private Integer keepCleanTime;

    /**
     *
     * 清洁保持时间增加次数上限(0为不限制)
     * product.clean_limit
     *
     * @mbg.generated
     */
    private Integer cleanLimit;

    /**
     *
     * 是否在商店显示
     * product.is_show
     *
     * @mbg.generated
     */
    private Boolean isShow;

    /**
     *
     * 类型，0小鸡，1小鸡道具
     * product.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * 状态，0下架，1上架
     * product.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 更新时间
     * product.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.num
     *
     * @return the value of product.num
     *
     * @mbg.generated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.num
     *
     * @param num the value for product.num
     *
     * @mbg.generated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img_path
     *
     * @return the value of product.img_path
     *
     * @mbg.generated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img_path
     *
     * @param imgPath the value for product.img_path
     *
     * @mbg.generated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.intro
     *
     * @return the value of product.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.intro
     *
     * @param intro the value for product.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.original_price
     *
     * @return the value of product.original_price
     *
     * @mbg.generated
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.original_price
     *
     * @param originalPrice the value for product.original_price
     *
     * @mbg.generated
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.joyful_val
     *
     * @return the value of product.joyful_val
     *
     * @mbg.generated
     */
    public Integer getJoyfulVal() {
        return joyfulVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.joyful_val
     *
     * @param joyfulVal the value for product.joyful_val
     *
     * @mbg.generated
     */
    public void setJoyfulVal(Integer joyfulVal) {
        this.joyfulVal = joyfulVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_joyful_first
     *
     * @return the value of product.is_joyful_first
     *
     * @mbg.generated
     */
    public Boolean getIsJoyfulFirst() {
        return isJoyfulFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_joyful_first
     *
     * @param isJoyfulFirst the value for product.is_joyful_first
     *
     * @mbg.generated
     */
    public void setIsJoyfulFirst(Boolean isJoyfulFirst) {
        this.isJoyfulFirst = isJoyfulFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.joyful_limit
     *
     * @return the value of product.joyful_limit
     *
     * @mbg.generated
     */
    public Integer getJoyfulLimit() {
        return joyfulLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.joyful_limit
     *
     * @param joyfulLimit the value for product.joyful_limit
     *
     * @mbg.generated
     */
    public void setJoyfulLimit(Integer joyfulLimit) {
        this.joyfulLimit = joyfulLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.growth_val
     *
     * @return the value of product.growth_val
     *
     * @mbg.generated
     */
    public Integer getGrowthVal() {
        return growthVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.growth_val
     *
     * @param growthVal the value for product.growth_val
     *
     * @mbg.generated
     */
    public void setGrowthVal(Integer growthVal) {
        this.growthVal = growthVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_growth_first
     *
     * @return the value of product.is_growth_first
     *
     * @mbg.generated
     */
    public Boolean getIsGrowthFirst() {
        return isGrowthFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_growth_first
     *
     * @param isGrowthFirst the value for product.is_growth_first
     *
     * @mbg.generated
     */
    public void setIsGrowthFirst(Boolean isGrowthFirst) {
        this.isGrowthFirst = isGrowthFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.growth_limit
     *
     * @return the value of product.growth_limit
     *
     * @mbg.generated
     */
    public Integer getGrowthLimit() {
        return growthLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.growth_limit
     *
     * @param growthLimit the value for product.growth_limit
     *
     * @mbg.generated
     */
    public void setGrowthLimit(Integer growthLimit) {
        this.growthLimit = growthLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.full_val
     *
     * @return the value of product.full_val
     *
     * @mbg.generated
     */
    public Integer getFullVal() {
        return fullVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.full_val
     *
     * @param fullVal the value for product.full_val
     *
     * @mbg.generated
     */
    public void setFullVal(Integer fullVal) {
        this.fullVal = fullVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_full_first
     *
     * @return the value of product.is_full_first
     *
     * @mbg.generated
     */
    public Boolean getIsFullFirst() {
        return isFullFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_full_first
     *
     * @param isFullFirst the value for product.is_full_first
     *
     * @mbg.generated
     */
    public void setIsFullFirst(Boolean isFullFirst) {
        this.isFullFirst = isFullFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.full_limit
     *
     * @return the value of product.full_limit
     *
     * @mbg.generated
     */
    public Integer getFullLimit() {
        return fullLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.full_limit
     *
     * @param fullLimit the value for product.full_limit
     *
     * @mbg.generated
     */
    public void setFullLimit(Integer fullLimit) {
        this.fullLimit = fullLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.day_usage_limit
     *
     * @return the value of product.day_usage_limit
     *
     * @mbg.generated
     */
    public Integer getDayUsageLimit() {
        return dayUsageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.day_usage_limit
     *
     * @param dayUsageLimit the value for product.day_usage_limit
     *
     * @mbg.generated
     */
    public void setDayUsageLimit(Integer dayUsageLimit) {
        this.dayUsageLimit = dayUsageLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.keep_clean_time
     *
     * @return the value of product.keep_clean_time
     *
     * @mbg.generated
     */
    public Integer getKeepCleanTime() {
        return keepCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.keep_clean_time
     *
     * @param keepCleanTime the value for product.keep_clean_time
     *
     * @mbg.generated
     */
    public void setKeepCleanTime(Integer keepCleanTime) {
        this.keepCleanTime = keepCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.clean_limit
     *
     * @return the value of product.clean_limit
     *
     * @mbg.generated
     */
    public Integer getCleanLimit() {
        return cleanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.clean_limit
     *
     * @param cleanLimit the value for product.clean_limit
     *
     * @mbg.generated
     */
    public void setCleanLimit(Integer cleanLimit) {
        this.cleanLimit = cleanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_show
     *
     * @return the value of product.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_show
     *
     * @param isShow the value for product.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_modified
     *
     * @return the value of product.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_modified
     *
     * @param gmtModified the value for product.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_create
     *
     * @return the value of product.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_create
     *
     * @param gmtCreate the value for product.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}