package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductOrderDO implements Serializable {
    /**
     *
     * 主键
     * product_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 订单编号
     * product_order.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     *
     * 商品id
     * product_order.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * 商品编号
     * product_order.product_num
     *
     * @mbg.generated
     */
    private String productNum;

    /**
     *
     * 商品名称
     * product_order.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * 商品图片
     * product_order.product_img_path
     *
     * @mbg.generated
     */
    private String productImgPath;

    /**
     *
     * 用户编号
     * product_order.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 数量
     * product_order.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * 单价
     * product_order.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * 总价
     * product_order.total_price
     *
     * @mbg.generated
     */
    private BigDecimal totalPrice;

    /**
     *
     * 第三方支付编号
     * product_order.pay_transaction_id
     *
     * @mbg.generated
     */
    private String payTransactionId;

    /**
     *
     * 支付备注
     * product_order.pay_remark
     *
     * @mbg.generated
     */
    private String payRemark;

    /**
     *
     * 订单状态(1-待付款|2-交易成功|3-交易失败)
     * product_order.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * 更新时间
     * product_order.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * product_order.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.id
     *
     * @return the value of product_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.id
     *
     * @param id the value for product_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.order_num
     *
     * @return the value of product_order.order_num
     *
     * @mbg.generated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.order_num
     *
     * @param orderNum the value for product_order.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.product_id
     *
     * @return the value of product_order.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.product_id
     *
     * @param productId the value for product_order.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.product_num
     *
     * @return the value of product_order.product_num
     *
     * @mbg.generated
     */
    public String getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.product_num
     *
     * @param productNum the value for product_order.product_num
     *
     * @mbg.generated
     */
    public void setProductNum(String productNum) {
        this.productNum = productNum == null ? null : productNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.product_name
     *
     * @return the value of product_order.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.product_name
     *
     * @param productName the value for product_order.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.product_img_path
     *
     * @return the value of product_order.product_img_path
     *
     * @mbg.generated
     */
    public String getProductImgPath() {
        return productImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.product_img_path
     *
     * @param productImgPath the value for product_order.product_img_path
     *
     * @mbg.generated
     */
    public void setProductImgPath(String productImgPath) {
        this.productImgPath = productImgPath == null ? null : productImgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.member_num
     *
     * @return the value of product_order.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.member_num
     *
     * @param memberNum the value for product_order.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.quantity
     *
     * @return the value of product_order.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.quantity
     *
     * @param quantity the value for product_order.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.price
     *
     * @return the value of product_order.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.price
     *
     * @param price the value for product_order.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.total_price
     *
     * @return the value of product_order.total_price
     *
     * @mbg.generated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.total_price
     *
     * @param totalPrice the value for product_order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.pay_transaction_id
     *
     * @return the value of product_order.pay_transaction_id
     *
     * @mbg.generated
     */
    public String getPayTransactionId() {
        return payTransactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.pay_transaction_id
     *
     * @param payTransactionId the value for product_order.pay_transaction_id
     *
     * @mbg.generated
     */
    public void setPayTransactionId(String payTransactionId) {
        this.payTransactionId = payTransactionId == null ? null : payTransactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.pay_remark
     *
     * @return the value of product_order.pay_remark
     *
     * @mbg.generated
     */
    public String getPayRemark() {
        return payRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.pay_remark
     *
     * @param payRemark the value for product_order.pay_remark
     *
     * @mbg.generated
     */
    public void setPayRemark(String payRemark) {
        this.payRemark = payRemark == null ? null : payRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.status
     *
     * @return the value of product_order.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.status
     *
     * @param status the value for product_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.gmt_modified
     *
     * @return the value of product_order.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.gmt_modified
     *
     * @param gmtModified the value for product_order.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.gmt_create
     *
     * @return the value of product_order.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.gmt_create
     *
     * @param gmtCreate the value for product_order.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}