package com.lawu.chick.repository.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public ProductDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andImgPathIsNull() {
            addCriterion("img_path is null");
            return (Criteria) this;
        }

        public Criteria andImgPathIsNotNull() {
            addCriterion("img_path is not null");
            return (Criteria) this;
        }

        public Criteria andImgPathEqualTo(String value) {
            addCriterion("img_path =", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotEqualTo(String value) {
            addCriterion("img_path <>", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThan(String value) {
            addCriterion("img_path >", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathGreaterThanOrEqualTo(String value) {
            addCriterion("img_path >=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThan(String value) {
            addCriterion("img_path <", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLessThanOrEqualTo(String value) {
            addCriterion("img_path <=", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathLike(String value) {
            addCriterion("img_path like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotLike(String value) {
            addCriterion("img_path not like", value, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathIn(List<String> values) {
            addCriterion("img_path in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotIn(List<String> values) {
            addCriterion("img_path not in", values, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathBetween(String value1, String value2) {
            addCriterion("img_path between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andImgPathNotBetween(String value1, String value2) {
            addCriterion("img_path not between", value1, value2, "imgPath");
            return (Criteria) this;
        }

        public Criteria andIntroIsNull() {
            addCriterion("intro is null");
            return (Criteria) this;
        }

        public Criteria andIntroIsNotNull() {
            addCriterion("intro is not null");
            return (Criteria) this;
        }

        public Criteria andIntroEqualTo(String value) {
            addCriterion("intro =", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotEqualTo(String value) {
            addCriterion("intro <>", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThan(String value) {
            addCriterion("intro >", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThanOrEqualTo(String value) {
            addCriterion("intro >=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThan(String value) {
            addCriterion("intro <", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThanOrEqualTo(String value) {
            addCriterion("intro <=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLike(String value) {
            addCriterion("intro like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotLike(String value) {
            addCriterion("intro not like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroIn(List<String> values) {
            addCriterion("intro in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotIn(List<String> values) {
            addCriterion("intro not in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroBetween(String value1, String value2) {
            addCriterion("intro between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotBetween(String value1, String value2) {
            addCriterion("intro not between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNull() {
            addCriterion("original_price is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNotNull() {
            addCriterion("original_price is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceEqualTo(BigDecimal value) {
            addCriterion("original_price =", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotEqualTo(BigDecimal value) {
            addCriterion("original_price <>", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThan(BigDecimal value) {
            addCriterion("original_price >", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("original_price >=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThan(BigDecimal value) {
            addCriterion("original_price <", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("original_price <=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIn(List<BigDecimal> values) {
            addCriterion("original_price in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotIn(List<BigDecimal> values) {
            addCriterion("original_price not in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("original_price between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("original_price not between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andJoyfulValIsNull() {
            addCriterion("joyful_val is null");
            return (Criteria) this;
        }

        public Criteria andJoyfulValIsNotNull() {
            addCriterion("joyful_val is not null");
            return (Criteria) this;
        }

        public Criteria andJoyfulValEqualTo(Integer value) {
            addCriterion("joyful_val =", value, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValNotEqualTo(Integer value) {
            addCriterion("joyful_val <>", value, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValGreaterThan(Integer value) {
            addCriterion("joyful_val >", value, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValGreaterThanOrEqualTo(Integer value) {
            addCriterion("joyful_val >=", value, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValLessThan(Integer value) {
            addCriterion("joyful_val <", value, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValLessThanOrEqualTo(Integer value) {
            addCriterion("joyful_val <=", value, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValIn(List<Integer> values) {
            addCriterion("joyful_val in", values, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValNotIn(List<Integer> values) {
            addCriterion("joyful_val not in", values, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValBetween(Integer value1, Integer value2) {
            addCriterion("joyful_val between", value1, value2, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andJoyfulValNotBetween(Integer value1, Integer value2) {
            addCriterion("joyful_val not between", value1, value2, "joyfulVal");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstIsNull() {
            addCriterion("is_joyful_first is null");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstIsNotNull() {
            addCriterion("is_joyful_first is not null");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstEqualTo(Boolean value) {
            addCriterion("is_joyful_first =", value, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstNotEqualTo(Boolean value) {
            addCriterion("is_joyful_first <>", value, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstGreaterThan(Boolean value) {
            addCriterion("is_joyful_first >", value, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_joyful_first >=", value, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstLessThan(Boolean value) {
            addCriterion("is_joyful_first <", value, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstLessThanOrEqualTo(Boolean value) {
            addCriterion("is_joyful_first <=", value, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstIn(List<Boolean> values) {
            addCriterion("is_joyful_first in", values, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstNotIn(List<Boolean> values) {
            addCriterion("is_joyful_first not in", values, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstBetween(Boolean value1, Boolean value2) {
            addCriterion("is_joyful_first between", value1, value2, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andIsJoyfulFirstNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_joyful_first not between", value1, value2, "isJoyfulFirst");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitIsNull() {
            addCriterion("joyful_limit is null");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitIsNotNull() {
            addCriterion("joyful_limit is not null");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitEqualTo(Integer value) {
            addCriterion("joyful_limit =", value, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitNotEqualTo(Integer value) {
            addCriterion("joyful_limit <>", value, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitGreaterThan(Integer value) {
            addCriterion("joyful_limit >", value, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("joyful_limit >=", value, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitLessThan(Integer value) {
            addCriterion("joyful_limit <", value, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitLessThanOrEqualTo(Integer value) {
            addCriterion("joyful_limit <=", value, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitIn(List<Integer> values) {
            addCriterion("joyful_limit in", values, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitNotIn(List<Integer> values) {
            addCriterion("joyful_limit not in", values, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitBetween(Integer value1, Integer value2) {
            addCriterion("joyful_limit between", value1, value2, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andJoyfulLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("joyful_limit not between", value1, value2, "joyfulLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthValIsNull() {
            addCriterion("growth_val is null");
            return (Criteria) this;
        }

        public Criteria andGrowthValIsNotNull() {
            addCriterion("growth_val is not null");
            return (Criteria) this;
        }

        public Criteria andGrowthValEqualTo(Integer value) {
            addCriterion("growth_val =", value, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValNotEqualTo(Integer value) {
            addCriterion("growth_val <>", value, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValGreaterThan(Integer value) {
            addCriterion("growth_val >", value, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValGreaterThanOrEqualTo(Integer value) {
            addCriterion("growth_val >=", value, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValLessThan(Integer value) {
            addCriterion("growth_val <", value, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValLessThanOrEqualTo(Integer value) {
            addCriterion("growth_val <=", value, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValIn(List<Integer> values) {
            addCriterion("growth_val in", values, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValNotIn(List<Integer> values) {
            addCriterion("growth_val not in", values, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValBetween(Integer value1, Integer value2) {
            addCriterion("growth_val between", value1, value2, "growthVal");
            return (Criteria) this;
        }

        public Criteria andGrowthValNotBetween(Integer value1, Integer value2) {
            addCriterion("growth_val not between", value1, value2, "growthVal");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstIsNull() {
            addCriterion("is_growth_first is null");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstIsNotNull() {
            addCriterion("is_growth_first is not null");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstEqualTo(Boolean value) {
            addCriterion("is_growth_first =", value, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstNotEqualTo(Boolean value) {
            addCriterion("is_growth_first <>", value, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstGreaterThan(Boolean value) {
            addCriterion("is_growth_first >", value, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_growth_first >=", value, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstLessThan(Boolean value) {
            addCriterion("is_growth_first <", value, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstLessThanOrEqualTo(Boolean value) {
            addCriterion("is_growth_first <=", value, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstIn(List<Boolean> values) {
            addCriterion("is_growth_first in", values, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstNotIn(List<Boolean> values) {
            addCriterion("is_growth_first not in", values, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstBetween(Boolean value1, Boolean value2) {
            addCriterion("is_growth_first between", value1, value2, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andIsGrowthFirstNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_growth_first not between", value1, value2, "isGrowthFirst");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitIsNull() {
            addCriterion("growth_limit is null");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitIsNotNull() {
            addCriterion("growth_limit is not null");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitEqualTo(Integer value) {
            addCriterion("growth_limit =", value, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitNotEqualTo(Integer value) {
            addCriterion("growth_limit <>", value, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitGreaterThan(Integer value) {
            addCriterion("growth_limit >", value, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("growth_limit >=", value, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitLessThan(Integer value) {
            addCriterion("growth_limit <", value, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitLessThanOrEqualTo(Integer value) {
            addCriterion("growth_limit <=", value, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitIn(List<Integer> values) {
            addCriterion("growth_limit in", values, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitNotIn(List<Integer> values) {
            addCriterion("growth_limit not in", values, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitBetween(Integer value1, Integer value2) {
            addCriterion("growth_limit between", value1, value2, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andGrowthLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("growth_limit not between", value1, value2, "growthLimit");
            return (Criteria) this;
        }

        public Criteria andFullValIsNull() {
            addCriterion("full_val is null");
            return (Criteria) this;
        }

        public Criteria andFullValIsNotNull() {
            addCriterion("full_val is not null");
            return (Criteria) this;
        }

        public Criteria andFullValEqualTo(Integer value) {
            addCriterion("full_val =", value, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValNotEqualTo(Integer value) {
            addCriterion("full_val <>", value, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValGreaterThan(Integer value) {
            addCriterion("full_val >", value, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValGreaterThanOrEqualTo(Integer value) {
            addCriterion("full_val >=", value, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValLessThan(Integer value) {
            addCriterion("full_val <", value, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValLessThanOrEqualTo(Integer value) {
            addCriterion("full_val <=", value, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValIn(List<Integer> values) {
            addCriterion("full_val in", values, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValNotIn(List<Integer> values) {
            addCriterion("full_val not in", values, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValBetween(Integer value1, Integer value2) {
            addCriterion("full_val between", value1, value2, "fullVal");
            return (Criteria) this;
        }

        public Criteria andFullValNotBetween(Integer value1, Integer value2) {
            addCriterion("full_val not between", value1, value2, "fullVal");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstIsNull() {
            addCriterion("is_full_first is null");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstIsNotNull() {
            addCriterion("is_full_first is not null");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstEqualTo(Boolean value) {
            addCriterion("is_full_first =", value, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstNotEqualTo(Boolean value) {
            addCriterion("is_full_first <>", value, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstGreaterThan(Boolean value) {
            addCriterion("is_full_first >", value, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_full_first >=", value, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstLessThan(Boolean value) {
            addCriterion("is_full_first <", value, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstLessThanOrEqualTo(Boolean value) {
            addCriterion("is_full_first <=", value, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstIn(List<Boolean> values) {
            addCriterion("is_full_first in", values, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstNotIn(List<Boolean> values) {
            addCriterion("is_full_first not in", values, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstBetween(Boolean value1, Boolean value2) {
            addCriterion("is_full_first between", value1, value2, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andIsFullFirstNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_full_first not between", value1, value2, "isFullFirst");
            return (Criteria) this;
        }

        public Criteria andFullLimitIsNull() {
            addCriterion("full_limit is null");
            return (Criteria) this;
        }

        public Criteria andFullLimitIsNotNull() {
            addCriterion("full_limit is not null");
            return (Criteria) this;
        }

        public Criteria andFullLimitEqualTo(Integer value) {
            addCriterion("full_limit =", value, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitNotEqualTo(Integer value) {
            addCriterion("full_limit <>", value, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitGreaterThan(Integer value) {
            addCriterion("full_limit >", value, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("full_limit >=", value, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitLessThan(Integer value) {
            addCriterion("full_limit <", value, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitLessThanOrEqualTo(Integer value) {
            addCriterion("full_limit <=", value, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitIn(List<Integer> values) {
            addCriterion("full_limit in", values, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitNotIn(List<Integer> values) {
            addCriterion("full_limit not in", values, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitBetween(Integer value1, Integer value2) {
            addCriterion("full_limit between", value1, value2, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andFullLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("full_limit not between", value1, value2, "fullLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitIsNull() {
            addCriterion("day_usage_limit is null");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitIsNotNull() {
            addCriterion("day_usage_limit is not null");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitEqualTo(Integer value) {
            addCriterion("day_usage_limit =", value, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitNotEqualTo(Integer value) {
            addCriterion("day_usage_limit <>", value, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitGreaterThan(Integer value) {
            addCriterion("day_usage_limit >", value, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_usage_limit >=", value, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitLessThan(Integer value) {
            addCriterion("day_usage_limit <", value, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitLessThanOrEqualTo(Integer value) {
            addCriterion("day_usage_limit <=", value, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitIn(List<Integer> values) {
            addCriterion("day_usage_limit in", values, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitNotIn(List<Integer> values) {
            addCriterion("day_usage_limit not in", values, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitBetween(Integer value1, Integer value2) {
            addCriterion("day_usage_limit between", value1, value2, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andDayUsageLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("day_usage_limit not between", value1, value2, "dayUsageLimit");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeIsNull() {
            addCriterion("keep_clean_time is null");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeIsNotNull() {
            addCriterion("keep_clean_time is not null");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeEqualTo(Integer value) {
            addCriterion("keep_clean_time =", value, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeNotEqualTo(Integer value) {
            addCriterion("keep_clean_time <>", value, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeGreaterThan(Integer value) {
            addCriterion("keep_clean_time >", value, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("keep_clean_time >=", value, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeLessThan(Integer value) {
            addCriterion("keep_clean_time <", value, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeLessThanOrEqualTo(Integer value) {
            addCriterion("keep_clean_time <=", value, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeIn(List<Integer> values) {
            addCriterion("keep_clean_time in", values, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeNotIn(List<Integer> values) {
            addCriterion("keep_clean_time not in", values, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeBetween(Integer value1, Integer value2) {
            addCriterion("keep_clean_time between", value1, value2, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andKeepCleanTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("keep_clean_time not between", value1, value2, "keepCleanTime");
            return (Criteria) this;
        }

        public Criteria andCleanLimitIsNull() {
            addCriterion("clean_limit is null");
            return (Criteria) this;
        }

        public Criteria andCleanLimitIsNotNull() {
            addCriterion("clean_limit is not null");
            return (Criteria) this;
        }

        public Criteria andCleanLimitEqualTo(Integer value) {
            addCriterion("clean_limit =", value, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitNotEqualTo(Integer value) {
            addCriterion("clean_limit <>", value, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitGreaterThan(Integer value) {
            addCriterion("clean_limit >", value, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("clean_limit >=", value, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitLessThan(Integer value) {
            addCriterion("clean_limit <", value, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitLessThanOrEqualTo(Integer value) {
            addCriterion("clean_limit <=", value, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitIn(List<Integer> values) {
            addCriterion("clean_limit in", values, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitNotIn(List<Integer> values) {
            addCriterion("clean_limit not in", values, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitBetween(Integer value1, Integer value2) {
            addCriterion("clean_limit between", value1, value2, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andCleanLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("clean_limit not between", value1, value2, "cleanLimit");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNull() {
            addCriterion("is_show is null");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNotNull() {
            addCriterion("is_show is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowEqualTo(Boolean value) {
            addCriterion("is_show =", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotEqualTo(Boolean value) {
            addCriterion("is_show <>", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThan(Boolean value) {
            addCriterion("is_show >", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_show >=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThan(Boolean value) {
            addCriterion("is_show <", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThanOrEqualTo(Boolean value) {
            addCriterion("is_show <=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowIn(List<Boolean> values) {
            addCriterion("is_show in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotIn(List<Boolean> values) {
            addCriterion("is_show not in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowBetween(Boolean value1, Boolean value2) {
            addCriterion("is_show between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_show not between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}