package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class RangelandEventRecordDO implements Serializable {
    /**
     *
     * 主键
     * rangeland_event_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * rangeland_event_record.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 小鸡编号
     * rangeland_event_record.chicken_num
     *
     * @mbg.generated
     */
    private String chickenNum;

    /**
     *
     * 标题
     * rangeland_event_record.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * 涉及属性类型，0无 1清洁度，2愉悦值，3成长值，4饱腹值，5鸡蛋
     * rangeland_event_record.attr_type
     *
     * @mbg.generated
     */
    private Byte attrType;

    /**
     *
     * 事件因子，0时间 1喂养 2处于/未处于牧场 3处于/未处于鸡舍 4打扫 5放养 6治疗/放弃治疗  7鸡蛋操作
     * rangeland_event_record.event_factor
     *
     * @mbg.generated
     */
    private Byte eventFactor;

    /**
     *
     * 0无 1-增加2-减少
     * rangeland_event_record.direction
     *
     * @mbg.generated
     */
    private Byte direction;

    /**
     *
     * 值
     * rangeland_event_record.val
     *
     * @mbg.generated
     */
    private BigDecimal val;

    /**
     *
     * 0系统，1主人，2好友
     * rangeland_event_record.source
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     *
     * 来源好友用户编号
     * rangeland_event_record.friend_num
     *
     * @mbg.generated
     */
    private String friendNum;

    /**
     *
     * 事件时间
     * rangeland_event_record.event_time
     *
     * @mbg.generated
     */
    private Date eventTime;

    /**
     *
     * 创建时间
     * rangeland_event_record.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.id
     *
     * @return the value of rangeland_event_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.id
     *
     * @param id the value for rangeland_event_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.member_num
     *
     * @return the value of rangeland_event_record.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.member_num
     *
     * @param memberNum the value for rangeland_event_record.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.chicken_num
     *
     * @return the value of rangeland_event_record.chicken_num
     *
     * @mbg.generated
     */
    public String getChickenNum() {
        return chickenNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.chicken_num
     *
     * @param chickenNum the value for rangeland_event_record.chicken_num
     *
     * @mbg.generated
     */
    public void setChickenNum(String chickenNum) {
        this.chickenNum = chickenNum == null ? null : chickenNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.title
     *
     * @return the value of rangeland_event_record.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.title
     *
     * @param title the value for rangeland_event_record.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.attr_type
     *
     * @return the value of rangeland_event_record.attr_type
     *
     * @mbg.generated
     */
    public Byte getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.attr_type
     *
     * @param attrType the value for rangeland_event_record.attr_type
     *
     * @mbg.generated
     */
    public void setAttrType(Byte attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.event_factor
     *
     * @return the value of rangeland_event_record.event_factor
     *
     * @mbg.generated
     */
    public Byte getEventFactor() {
        return eventFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.event_factor
     *
     * @param eventFactor the value for rangeland_event_record.event_factor
     *
     * @mbg.generated
     */
    public void setEventFactor(Byte eventFactor) {
        this.eventFactor = eventFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.direction
     *
     * @return the value of rangeland_event_record.direction
     *
     * @mbg.generated
     */
    public Byte getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.direction
     *
     * @param direction the value for rangeland_event_record.direction
     *
     * @mbg.generated
     */
    public void setDirection(Byte direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.val
     *
     * @return the value of rangeland_event_record.val
     *
     * @mbg.generated
     */
    public BigDecimal getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.val
     *
     * @param val the value for rangeland_event_record.val
     *
     * @mbg.generated
     */
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.source
     *
     * @return the value of rangeland_event_record.source
     *
     * @mbg.generated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.source
     *
     * @param source the value for rangeland_event_record.source
     *
     * @mbg.generated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.friend_num
     *
     * @return the value of rangeland_event_record.friend_num
     *
     * @mbg.generated
     */
    public String getFriendNum() {
        return friendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.friend_num
     *
     * @param friendNum the value for rangeland_event_record.friend_num
     *
     * @mbg.generated
     */
    public void setFriendNum(String friendNum) {
        this.friendNum = friendNum == null ? null : friendNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.event_time
     *
     * @return the value of rangeland_event_record.event_time
     *
     * @mbg.generated
     */
    public Date getEventTime() {
        return eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.event_time
     *
     * @param eventTime the value for rangeland_event_record.event_time
     *
     * @mbg.generated
     */
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland_event_record.gmt_create
     *
     * @return the value of rangeland_event_record.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland_event_record.gmt_create
     *
     * @param gmtCreate the value for rangeland_event_record.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}