package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class RangelandDO implements Serializable {
    /**
     *
     * 主键
     * rangeland.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 所属用户编号
     * rangeland.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 外部清洁度
     * rangeland.external_cleanness
     *
     * @mbg.generated
     */
    private Integer externalCleanness;

    /**
     *
     * 产生农场垃圾时间
     * rangeland.external_clean_time
     *
     * @mbg.generated
     */
    private Date externalCleanTime;

    /**
     *
     * 更新时间
     * rangeland.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * 创建时间
     * rangeland.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * 小鸡处于牧场外部计时开始时间
     * rangeland.outside_time
     *
     * @mbg.generated
     */
    private Date outsideTime;

    /**
     *
     * 小鸡处于牧场外部总时长，单位分钟
     * rangeland.outside_duration
     *
     * @mbg.generated
     */
    private Integer outsideDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rangeland
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.id
     *
     * @return the value of rangeland.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.id
     *
     * @param id the value for rangeland.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.member_num
     *
     * @return the value of rangeland.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.member_num
     *
     * @param memberNum the value for rangeland.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.external_cleanness
     *
     * @return the value of rangeland.external_cleanness
     *
     * @mbg.generated
     */
    public Integer getExternalCleanness() {
        return externalCleanness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.external_cleanness
     *
     * @param externalCleanness the value for rangeland.external_cleanness
     *
     * @mbg.generated
     */
    public void setExternalCleanness(Integer externalCleanness) {
        this.externalCleanness = externalCleanness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.external_clean_time
     *
     * @return the value of rangeland.external_clean_time
     *
     * @mbg.generated
     */
    public Date getExternalCleanTime() {
        return externalCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.external_clean_time
     *
     * @param externalCleanTime the value for rangeland.external_clean_time
     *
     * @mbg.generated
     */
    public void setExternalCleanTime(Date externalCleanTime) {
        this.externalCleanTime = externalCleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.gmt_modified
     *
     * @return the value of rangeland.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.gmt_modified
     *
     * @param gmtModified the value for rangeland.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.gmt_create
     *
     * @return the value of rangeland.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.gmt_create
     *
     * @param gmtCreate the value for rangeland.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.outside_time
     *
     * @return the value of rangeland.outside_time
     *
     * @mbg.generated
     */
    public Date getOutsideTime() {
        return outsideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.outside_time
     *
     * @param outsideTime the value for rangeland.outside_time
     *
     * @mbg.generated
     */
    public void setOutsideTime(Date outsideTime) {
        this.outsideTime = outsideTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangeland.outside_duration
     *
     * @return the value of rangeland.outside_duration
     *
     * @mbg.generated
     */
    public Integer getOutsideDuration() {
        return outsideDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangeland.outside_duration
     *
     * @param outsideDuration the value for rangeland.outside_duration
     *
     * @mbg.generated
     */
    public void setOutsideDuration(Integer outsideDuration) {
        this.outsideDuration = outsideDuration;
    }
}