package com.lawu.chick.repository.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysConfigDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public SysConfigDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeIsNull() {
            addCriterion("chicken_effective_time is null");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeIsNotNull() {
            addCriterion("chicken_effective_time is not null");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeEqualTo(Date value) {
            addCriterion("chicken_effective_time =", value, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeNotEqualTo(Date value) {
            addCriterion("chicken_effective_time <>", value, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeGreaterThan(Date value) {
            addCriterion("chicken_effective_time >", value, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("chicken_effective_time >=", value, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeLessThan(Date value) {
            addCriterion("chicken_effective_time <", value, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("chicken_effective_time <=", value, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeIn(List<Date> values) {
            addCriterion("chicken_effective_time in", values, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeNotIn(List<Date> values) {
            addCriterion("chicken_effective_time not in", values, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeBetween(Date value1, Date value2) {
            addCriterion("chicken_effective_time between", value1, value2, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andChickenEffectiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("chicken_effective_time not between", value1, value2, "chickenEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeIsNull() {
            addCriterion("egg_effective_time is null");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeIsNotNull() {
            addCriterion("egg_effective_time is not null");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeEqualTo(Date value) {
            addCriterion("egg_effective_time =", value, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeNotEqualTo(Date value) {
            addCriterion("egg_effective_time <>", value, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeGreaterThan(Date value) {
            addCriterion("egg_effective_time >", value, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("egg_effective_time >=", value, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeLessThan(Date value) {
            addCriterion("egg_effective_time <", value, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("egg_effective_time <=", value, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeIn(List<Date> values) {
            addCriterion("egg_effective_time in", values, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeNotIn(List<Date> values) {
            addCriterion("egg_effective_time not in", values, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeBetween(Date value1, Date value2) {
            addCriterion("egg_effective_time between", value1, value2, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andEggEffectiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("egg_effective_time not between", value1, value2, "eggEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeIsNull() {
            addCriterion("rangeland_effective_time is null");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeIsNotNull() {
            addCriterion("rangeland_effective_time is not null");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeEqualTo(Date value) {
            addCriterion("rangeland_effective_time =", value, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeNotEqualTo(Date value) {
            addCriterion("rangeland_effective_time <>", value, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeGreaterThan(Date value) {
            addCriterion("rangeland_effective_time >", value, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("rangeland_effective_time >=", value, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeLessThan(Date value) {
            addCriterion("rangeland_effective_time <", value, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("rangeland_effective_time <=", value, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeIn(List<Date> values) {
            addCriterion("rangeland_effective_time in", values, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeNotIn(List<Date> values) {
            addCriterion("rangeland_effective_time not in", values, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeBetween(Date value1, Date value2) {
            addCriterion("rangeland_effective_time between", value1, value2, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andRangelandEffectiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("rangeland_effective_time not between", value1, value2, "rangelandEffectiveTime");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}