package com.lawu.chick.repository.domain;

import java.io.Serializable;
import java.util.Date;

public class UserRelationDO implements Serializable {
    /**
     *
     * 主键
     * user_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * 用户编号
     * user_relation.member_num
     *
     * @mbg.generated
     */
    private String memberNum;

    /**
     *
     * 好友用户编号
     * user_relation.friend_num
     *
     * @mbg.generated
     */
    private String friendNum;

    /**
     *
     * 创建时间
     * user_relation.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.id
     *
     * @return the value of user_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.id
     *
     * @param id the value for user_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.member_num
     *
     * @return the value of user_relation.member_num
     *
     * @mbg.generated
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.member_num
     *
     * @param memberNum the value for user_relation.member_num
     *
     * @mbg.generated
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum == null ? null : memberNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.friend_num
     *
     * @return the value of user_relation.friend_num
     *
     * @mbg.generated
     */
    public String getFriendNum() {
        return friendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.friend_num
     *
     * @param friendNum the value for user_relation.friend_num
     *
     * @mbg.generated
     */
    public void setFriendNum(String friendNum) {
        this.friendNum = friendNum == null ? null : friendNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.gmt_create
     *
     * @return the value of user_relation.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.gmt_create
     *
     * @param gmtCreate the value for user_relation.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}