package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.ChickenDO;
import com.lawu.chick.repository.domain.ChickenDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChickenDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    long countByExample(ChickenDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int deleteByExample(ChickenDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int insert(ChickenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int insertSelective(ChickenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    List<ChickenDO> selectByExampleWithRowbounds(ChickenDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    List<ChickenDO> selectByExample(ChickenDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    ChickenDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChickenDO record, @Param("example") ChickenDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChickenDO record, @Param("example") ChickenDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChickenDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChickenDO record);
}