package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.ChickenCureTaskDO;
import com.lawu.chick.repository.domain.ChickenCureTaskDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChickenCureTaskDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    long countByExample(ChickenCureTaskDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int deleteByExample(ChickenCureTaskDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int insert(ChickenCureTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int insertSelective(ChickenCureTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    List<ChickenCureTaskDO> selectByExampleWithRowbounds(ChickenCureTaskDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    List<ChickenCureTaskDO> selectByExample(ChickenCureTaskDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    ChickenCureTaskDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChickenCureTaskDO record, @Param("example") ChickenCureTaskDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChickenCureTaskDO record, @Param("example") ChickenCureTaskDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChickenCureTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chicken_cure_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChickenCureTaskDO record);
}