package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.EggExchangeRecordDO;
import com.lawu.chick.repository.domain.EggExchangeRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EggExchangeRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    long countByExample(EggExchangeRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int deleteByExample(EggExchangeRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int insert(EggExchangeRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int insertSelective(EggExchangeRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    List<EggExchangeRecordDO> selectByExampleWithRowbounds(EggExchangeRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    List<EggExchangeRecordDO> selectByExample(EggExchangeRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    EggExchangeRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EggExchangeRecordDO record, @Param("example") EggExchangeRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EggExchangeRecordDO record, @Param("example") EggExchangeRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EggExchangeRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_exchange_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EggExchangeRecordDO record);
}