package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.EggReleaseRecordDO;
import com.lawu.chick.repository.domain.EggReleaseRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EggReleaseRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    long countByExample(EggReleaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int deleteByExample(EggReleaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int insert(EggReleaseRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int insertSelective(EggReleaseRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    List<EggReleaseRecordDO> selectByExampleWithRowbounds(EggReleaseRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    List<EggReleaseRecordDO> selectByExample(EggReleaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    EggReleaseRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EggReleaseRecordDO record, @Param("example") EggReleaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EggReleaseRecordDO record, @Param("example") EggReleaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EggReleaseRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table egg_release_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EggReleaseRecordDO record);
}