package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.GiftDO;
import com.lawu.chick.repository.domain.GiftDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GiftDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    long countByExample(GiftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int deleteByExample(GiftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int insert(GiftDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int insertSelective(GiftDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    List<GiftDO> selectByExampleWithRowbounds(GiftDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    List<GiftDO> selectByExample(GiftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    GiftDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GiftDO record, @Param("example") GiftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GiftDO record, @Param("example") GiftDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GiftDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GiftDO record);
}