package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.InventoryDetailDO;
import com.lawu.chick.repository.domain.InventoryDetailDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InventoryDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    long countByExample(InventoryDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int deleteByExample(InventoryDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int insert(InventoryDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int insertSelective(InventoryDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    List<InventoryDetailDO> selectByExampleWithRowbounds(InventoryDetailDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    List<InventoryDetailDO> selectByExample(InventoryDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    InventoryDetailDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InventoryDetailDO record, @Param("example") InventoryDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InventoryDetailDO record, @Param("example") InventoryDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InventoryDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InventoryDetailDO record);
}