package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.PraySignRuleDO;
import com.lawu.chick.repository.domain.PraySignRuleDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PraySignRuleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    long countByExample(PraySignRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int deleteByExample(PraySignRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int insert(PraySignRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int insertSelective(PraySignRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    List<PraySignRuleDO> selectByExampleWithRowbounds(PraySignRuleDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    List<PraySignRuleDO> selectByExample(PraySignRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    PraySignRuleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PraySignRuleDO record, @Param("example") PraySignRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PraySignRuleDO record, @Param("example") PraySignRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PraySignRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PraySignRuleDO record);
}