package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.PraySignRecordDO;
import com.lawu.chick.repository.domain.PraySignRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PraySignRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    long countByExample(PraySignRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int deleteByExample(PraySignRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int insert(PraySignRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int insertSelective(PraySignRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    List<PraySignRecordDO> selectByExampleWithRowbounds(PraySignRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    List<PraySignRecordDO> selectByExample(PraySignRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    PraySignRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PraySignRecordDO record, @Param("example") PraySignRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PraySignRecordDO record, @Param("example") PraySignRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PraySignRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PraySignRecordDO record);
}