package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.PraySignRewardsDO;
import com.lawu.chick.repository.domain.PraySignRewardsDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PraySignRewardsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    long countByExample(PraySignRewardsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int deleteByExample(PraySignRewardsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int insert(PraySignRewardsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int insertSelective(PraySignRewardsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    List<PraySignRewardsDO> selectByExampleWithRowbounds(PraySignRewardsDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    List<PraySignRewardsDO> selectByExample(PraySignRewardsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    PraySignRewardsDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PraySignRewardsDO record, @Param("example") PraySignRewardsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PraySignRewardsDO record, @Param("example") PraySignRewardsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PraySignRewardsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray_sign_rewards
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PraySignRewardsDO record);
}