package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.ProductOrderDO;
import com.lawu.chick.repository.domain.ProductOrderDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductOrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    long countByExample(ProductOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int deleteByExample(ProductOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int insert(ProductOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int insertSelective(ProductOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    List<ProductOrderDO> selectByExampleWithRowbounds(ProductOrderDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    List<ProductOrderDO> selectByExample(ProductOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    ProductOrderDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductOrderDO record, @Param("example") ProductOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductOrderDO record, @Param("example") ProductOrderDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductOrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductOrderDO record);
}