package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.RangelandEventRecordDO;
import com.lawu.chick.repository.domain.RangelandEventRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RangelandEventRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    long countByExample(RangelandEventRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int deleteByExample(RangelandEventRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int insert(RangelandEventRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int insertSelective(RangelandEventRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    List<RangelandEventRecordDO> selectByExampleWithRowbounds(RangelandEventRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    List<RangelandEventRecordDO> selectByExample(RangelandEventRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    RangelandEventRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RangelandEventRecordDO record, @Param("example") RangelandEventRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RangelandEventRecordDO record, @Param("example") RangelandEventRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RangelandEventRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangeland_event_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RangelandEventRecordDO record);
}