package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.SignInRecordDO;
import com.lawu.chick.repository.domain.SignInRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SignInRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    long countByExample(SignInRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int deleteByExample(SignInRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int insert(SignInRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int insertSelective(SignInRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    List<SignInRecordDO> selectByExampleWithRowbounds(SignInRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    List<SignInRecordDO> selectByExample(SignInRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    SignInRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SignInRecordDO record, @Param("example") SignInRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SignInRecordDO record, @Param("example") SignInRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SignInRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_in_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SignInRecordDO record);
}