package com.lawu.chick.repository.mapper;

import com.lawu.chick.repository.domain.UserRelationDO;
import com.lawu.chick.repository.domain.UserRelationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserRelationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    long countByExample(UserRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int deleteByExample(UserRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int insert(UserRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int insertSelective(UserRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    List<UserRelationDO> selectByExampleWithRowbounds(UserRelationDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    List<UserRelationDO> selectByExample(UserRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    UserRelationDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserRelationDO record, @Param("example") UserRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserRelationDO record, @Param("example") UserRelationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRelationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRelationDO record);
}